//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorsExport.ColaboradorSOAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Colaborador", Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    [System.SerializableAttribute()]
    public partial class Colaborador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        private int EMPRESAField;
        
        private int CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEField;
        
        private System.DateTime ADMISSAOField;
        
        private System.Nullable<int> CARGOField;
        
        private System.Nullable<int> SINDICATOField;
        
        private System.Nullable<int> LOCALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CENTROCUSTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOENDERECOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENDERECOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMEROENDERECOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPLEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BAIRROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MUNICIPIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONEField;
        
        private System.Nullable<System.DateTime> DATANASCIMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NACIONALIDADEField;
        
        private System.Nullable<int> LOCALNASCIMENTOField;
        
        private System.Nullable<int> ESTADOCIVILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        private int AGENCIAField;
        
        private System.Nullable<int> BANCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULOELEITORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SECAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTPSField;
        
        private System.Nullable<System.DateTime> RESCISAOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((this.EMPRESAField.Equals(value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((this.CODIGOField.Equals(value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NOME {
            get {
                return this.NOMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEField, value) != true)) {
                    this.NOMEField = value;
                    this.RaisePropertyChanged("NOME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime ADMISSAO {
            get {
                return this.ADMISSAOField;
            }
            set {
                if ((this.ADMISSAOField.Equals(value) != true)) {
                    this.ADMISSAOField = value;
                    this.RaisePropertyChanged("ADMISSAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> CARGO {
            get {
                return this.CARGOField;
            }
            set {
                if ((this.CARGOField.Equals(value) != true)) {
                    this.CARGOField = value;
                    this.RaisePropertyChanged("CARGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> SINDICATO {
            get {
                return this.SINDICATOField;
            }
            set {
                if ((this.SINDICATOField.Equals(value) != true)) {
                    this.SINDICATOField = value;
                    this.RaisePropertyChanged("SINDICATO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> LOCAL {
            get {
                return this.LOCALField;
            }
            set {
                if ((this.LOCALField.Equals(value) != true)) {
                    this.LOCALField = value;
                    this.RaisePropertyChanged("LOCAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CENTROCUSTO {
            get {
                return this.CENTROCUSTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CENTROCUSTOField, value) != true)) {
                    this.CENTROCUSTOField = value;
                    this.RaisePropertyChanged("CENTROCUSTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TIPOENDERECO {
            get {
                return this.TIPOENDERECOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOENDERECOField, value) != true)) {
                    this.TIPOENDERECOField = value;
                    this.RaisePropertyChanged("TIPOENDERECO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ENDERECO {
            get {
                return this.ENDERECOField;
            }
            set {
                if ((object.ReferenceEquals(this.ENDERECOField, value) != true)) {
                    this.ENDERECOField = value;
                    this.RaisePropertyChanged("ENDERECO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string NUMEROENDERECO {
            get {
                return this.NUMEROENDERECOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMEROENDERECOField, value) != true)) {
                    this.NUMEROENDERECOField = value;
                    this.RaisePropertyChanged("NUMEROENDERECO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string COMPLEMENTO {
            get {
                return this.COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPLEMENTOField, value) != true)) {
                    this.COMPLEMENTOField = value;
                    this.RaisePropertyChanged("COMPLEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string BAIRRO {
            get {
                return this.BAIRROField;
            }
            set {
                if ((object.ReferenceEquals(this.BAIRROField, value) != true)) {
                    this.BAIRROField = value;
                    this.RaisePropertyChanged("BAIRRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string MUNICIPIO {
            get {
                return this.MUNICIPIOField;
            }
            set {
                if ((object.ReferenceEquals(this.MUNICIPIOField, value) != true)) {
                    this.MUNICIPIOField = value;
                    this.RaisePropertyChanged("MUNICIPIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DDD {
            get {
                return this.DDDField;
            }
            set {
                if ((object.ReferenceEquals(this.DDDField, value) != true)) {
                    this.DDDField = value;
                    this.RaisePropertyChanged("DDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string TELEFONE {
            get {
                return this.TELEFONEField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONEField, value) != true)) {
                    this.TELEFONEField = value;
                    this.RaisePropertyChanged("TELEFONE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> DATANASCIMENTO {
            get {
                return this.DATANASCIMENTOField;
            }
            set {
                if ((this.DATANASCIMENTOField.Equals(value) != true)) {
                    this.DATANASCIMENTOField = value;
                    this.RaisePropertyChanged("DATANASCIMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string NACIONALIDADE {
            get {
                return this.NACIONALIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.NACIONALIDADEField, value) != true)) {
                    this.NACIONALIDADEField = value;
                    this.RaisePropertyChanged("NACIONALIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<int> LOCALNASCIMENTO {
            get {
                return this.LOCALNASCIMENTOField;
            }
            set {
                if ((this.LOCALNASCIMENTOField.Equals(value) != true)) {
                    this.LOCALNASCIMENTOField = value;
                    this.RaisePropertyChanged("LOCALNASCIMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<int> ESTADOCIVIL {
            get {
                return this.ESTADOCIVILField;
            }
            set {
                if ((this.ESTADOCIVILField.Equals(value) != true)) {
                    this.ESTADOCIVILField = value;
                    this.RaisePropertyChanged("ESTADOCIVIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string SEXO {
            get {
                return this.SEXOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXOField, value) != true)) {
                    this.SEXOField = value;
                    this.RaisePropertyChanged("SEXO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string PIS {
            get {
                return this.PISField;
            }
            set {
                if ((object.ReferenceEquals(this.PISField, value) != true)) {
                    this.PISField = value;
                    this.RaisePropertyChanged("PIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public int AGENCIA {
            get {
                return this.AGENCIAField;
            }
            set {
                if ((this.AGENCIAField.Equals(value) != true)) {
                    this.AGENCIAField = value;
                    this.RaisePropertyChanged("AGENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public System.Nullable<int> BANCO {
            get {
                return this.BANCOField;
            }
            set {
                if ((this.BANCOField.Equals(value) != true)) {
                    this.BANCOField = value;
                    this.RaisePropertyChanged("BANCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string CONTA {
            get {
                return this.CONTAField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTAField, value) != true)) {
                    this.CONTAField = value;
                    this.RaisePropertyChanged("CONTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string OBS {
            get {
                return this.OBSField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSField, value) != true)) {
                    this.OBSField = value;
                    this.RaisePropertyChanged("OBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string TITULOELEITOR {
            get {
                return this.TITULOELEITORField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULOELEITORField, value) != true)) {
                    this.TITULOELEITORField = value;
                    this.RaisePropertyChanged("TITULOELEITOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string ZONA {
            get {
                return this.ZONAField;
            }
            set {
                if ((object.ReferenceEquals(this.ZONAField, value) != true)) {
                    this.ZONAField = value;
                    this.RaisePropertyChanged("ZONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string SECAO {
            get {
                return this.SECAOField;
            }
            set {
                if ((object.ReferenceEquals(this.SECAOField, value) != true)) {
                    this.SECAOField = value;
                    this.RaisePropertyChanged("SECAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string CTPS {
            get {
                return this.CTPSField;
            }
            set {
                if ((object.ReferenceEquals(this.CTPSField, value) != true)) {
                    this.CTPSField = value;
                    this.RaisePropertyChanged("CTPS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public System.Nullable<System.DateTime> RESCISAO {
            get {
                return this.RESCISAOField;
            }
            set {
                if ((this.RESCISAOField.Equals(value) != true)) {
                    this.RESCISAOField = value;
                    this.RaisePropertyChanged("RESCISAO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/", ConfigurationName="ColaboradorSOAP.ColaboradorSoap")]
    public interface ColaboradorSoap {
        
        // CODEGEN: Generating message contract since element name ObterResult from namespace http://cardexpressbrasil.web2302.uni5.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/Obter", ReplyAction="*")]
        DoorsExport.ColaboradorSOAP.ObterResponse Obter(DoorsExport.ColaboradorSOAP.ObterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/Obter", ReplyAction="*")]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.ObterResponse> ObterAsync(DoorsExport.ColaboradorSOAP.ObterRequest request);
        
        // CODEGEN: Generating message contract since element name ObterTodosResult from namespace http://cardexpressbrasil.web2302.uni5.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/ObterTodos", ReplyAction="*")]
        DoorsExport.ColaboradorSOAP.ObterTodosResponse ObterTodos(DoorsExport.ColaboradorSOAP.ObterTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/ObterTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.ObterTodosResponse> ObterTodosAsync(DoorsExport.ColaboradorSOAP.ObterTodosRequest request);
        
        // CODEGEN: Generating message contract since element name colaborador from namespace http://cardexpressbrasil.web2302.uni5.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/Inserir", ReplyAction="*")]
        DoorsExport.ColaboradorSOAP.InserirResponse Inserir(DoorsExport.ColaboradorSOAP.InserirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/Inserir", ReplyAction="*")]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.InserirResponse> InserirAsync(DoorsExport.ColaboradorSOAP.InserirRequest request);
        
        // CODEGEN: Generating message contract since element name colaborador from namespace http://cardexpressbrasil.web2302.uni5.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/InserirVarios", ReplyAction="*")]
        DoorsExport.ColaboradorSOAP.InserirVariosResponse InserirVarios(DoorsExport.ColaboradorSOAP.InserirVariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/InserirVarios", ReplyAction="*")]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.InserirVariosResponse> InserirVariosAsync(DoorsExport.ColaboradorSOAP.InserirVariosRequest request);
        
        // CODEGEN: Generating message contract since element name colaborador from namespace http://cardexpressbrasil.web2302.uni5.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/Atualizar", ReplyAction="*")]
        DoorsExport.ColaboradorSOAP.AtualizarResponse Atualizar(DoorsExport.ColaboradorSOAP.AtualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cardexpressbrasil.web2302.uni5.net/Atualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.AtualizarResponse> AtualizarAsync(DoorsExport.ColaboradorSOAP.AtualizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obter", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.ObterRequestBody Body;
        
        public ObterRequest() {
        }
        
        public ObterRequest(DoorsExport.ColaboradorSOAP.ObterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class ObterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigo;
        
        public ObterRequestBody() {
        }
        
        public ObterRequestBody(int empresa, int codigo) {
            this.empresa = empresa;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterResponse", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.ObterResponseBody Body;
        
        public ObterResponse() {
        }
        
        public ObterResponse(DoorsExport.ColaboradorSOAP.ObterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class ObterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoorsExport.ColaboradorSOAP.Colaborador ObterResult;
        
        public ObterResponseBody() {
        }
        
        public ObterResponseBody(DoorsExport.ColaboradorSOAP.Colaborador ObterResult) {
            this.ObterResult = ObterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterTodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterTodos", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.ObterTodosRequestBody Body;
        
        public ObterTodosRequest() {
        }
        
        public ObterTodosRequest(DoorsExport.ColaboradorSOAP.ObterTodosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class ObterTodosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empresa;
        
        public ObterTodosRequestBody() {
        }
        
        public ObterTodosRequestBody(int empresa) {
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterTodosResponse", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.ObterTodosResponseBody Body;
        
        public ObterTodosResponse() {
        }
        
        public ObterTodosResponse(DoorsExport.ColaboradorSOAP.ObterTodosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class ObterTodosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoorsExport.ColaboradorSOAP.Colaborador[] ObterTodosResult;
        
        public ObterTodosResponseBody() {
        }
        
        public ObterTodosResponseBody(DoorsExport.ColaboradorSOAP.Colaborador[] ObterTodosResult) {
            this.ObterTodosResult = ObterTodosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inserir", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.InserirRequestBody Body;
        
        public InserirRequest() {
        }
        
        public InserirRequest(DoorsExport.ColaboradorSOAP.InserirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class InserirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoorsExport.ColaboradorSOAP.Colaborador colaborador;
        
        public InserirRequestBody() {
        }
        
        public InserirRequestBody(DoorsExport.ColaboradorSOAP.Colaborador colaborador) {
            this.colaborador = colaborador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirResponse", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.InserirResponseBody Body;
        
        public InserirResponse() {
        }
        
        public InserirResponse(DoorsExport.ColaboradorSOAP.InserirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InserirResponseBody {
        
        public InserirResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirVariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirVarios", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.InserirVariosRequestBody Body;
        
        public InserirVariosRequest() {
        }
        
        public InserirVariosRequest(DoorsExport.ColaboradorSOAP.InserirVariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class InserirVariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoorsExport.ColaboradorSOAP.Colaborador[] colaborador;
        
        public InserirVariosRequestBody() {
        }
        
        public InserirVariosRequestBody(DoorsExport.ColaboradorSOAP.Colaborador[] colaborador) {
            this.colaborador = colaborador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirVariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirVariosResponse", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.InserirVariosResponseBody Body;
        
        public InserirVariosResponse() {
        }
        
        public InserirVariosResponse(DoorsExport.ColaboradorSOAP.InserirVariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class InserirVariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InserirVariosResult;
        
        public InserirVariosResponseBody() {
        }
        
        public InserirVariosResponseBody(int InserirVariosResult) {
            this.InserirVariosResult = InserirVariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Atualizar", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.AtualizarRequestBody Body;
        
        public AtualizarRequest() {
        }
        
        public AtualizarRequest(DoorsExport.ColaboradorSOAP.AtualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class AtualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DoorsExport.ColaboradorSOAP.Colaborador colaborador;
        
        public AtualizarRequestBody() {
        }
        
        public AtualizarRequestBody(DoorsExport.ColaboradorSOAP.Colaborador colaborador) {
            this.colaborador = colaborador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarResponse", Namespace="http://cardexpressbrasil.web2302.uni5.net/", Order=0)]
        public DoorsExport.ColaboradorSOAP.AtualizarResponseBody Body;
        
        public AtualizarResponse() {
        }
        
        public AtualizarResponse(DoorsExport.ColaboradorSOAP.AtualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cardexpressbrasil.web2302.uni5.net/")]
    public partial class AtualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AtualizarResult;
        
        public AtualizarResponseBody() {
        }
        
        public AtualizarResponseBody(bool AtualizarResult) {
            this.AtualizarResult = AtualizarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColaboradorSoapChannel : DoorsExport.ColaboradorSOAP.ColaboradorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColaboradorSoapClient : System.ServiceModel.ClientBase<DoorsExport.ColaboradorSOAP.ColaboradorSoap>, DoorsExport.ColaboradorSOAP.ColaboradorSoap {
        
        public ColaboradorSoapClient() {
        }
        
        public ColaboradorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColaboradorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColaboradorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColaboradorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoorsExport.ColaboradorSOAP.ObterResponse DoorsExport.ColaboradorSOAP.ColaboradorSoap.Obter(DoorsExport.ColaboradorSOAP.ObterRequest request) {
            return base.Channel.Obter(request);
        }
        
        public DoorsExport.ColaboradorSOAP.Colaborador Obter(int empresa, int codigo) {
            DoorsExport.ColaboradorSOAP.ObterRequest inValue = new DoorsExport.ColaboradorSOAP.ObterRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.ObterRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.codigo = codigo;
            DoorsExport.ColaboradorSOAP.ObterResponse retVal = ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).Obter(inValue);
            return retVal.Body.ObterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.ObterResponse> DoorsExport.ColaboradorSOAP.ColaboradorSoap.ObterAsync(DoorsExport.ColaboradorSOAP.ObterRequest request) {
            return base.Channel.ObterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.ObterResponse> ObterAsync(int empresa, int codigo) {
            DoorsExport.ColaboradorSOAP.ObterRequest inValue = new DoorsExport.ColaboradorSOAP.ObterRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.ObterRequestBody();
            inValue.Body.empresa = empresa;
            inValue.Body.codigo = codigo;
            return ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).ObterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoorsExport.ColaboradorSOAP.ObterTodosResponse DoorsExport.ColaboradorSOAP.ColaboradorSoap.ObterTodos(DoorsExport.ColaboradorSOAP.ObterTodosRequest request) {
            return base.Channel.ObterTodos(request);
        }
        
        public DoorsExport.ColaboradorSOAP.Colaborador[] ObterTodos(int empresa) {
            DoorsExport.ColaboradorSOAP.ObterTodosRequest inValue = new DoorsExport.ColaboradorSOAP.ObterTodosRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.ObterTodosRequestBody();
            inValue.Body.empresa = empresa;
            DoorsExport.ColaboradorSOAP.ObterTodosResponse retVal = ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).ObterTodos(inValue);
            return retVal.Body.ObterTodosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.ObterTodosResponse> DoorsExport.ColaboradorSOAP.ColaboradorSoap.ObterTodosAsync(DoorsExport.ColaboradorSOAP.ObterTodosRequest request) {
            return base.Channel.ObterTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.ObterTodosResponse> ObterTodosAsync(int empresa) {
            DoorsExport.ColaboradorSOAP.ObterTodosRequest inValue = new DoorsExport.ColaboradorSOAP.ObterTodosRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.ObterTodosRequestBody();
            inValue.Body.empresa = empresa;
            return ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).ObterTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoorsExport.ColaboradorSOAP.InserirResponse DoorsExport.ColaboradorSOAP.ColaboradorSoap.Inserir(DoorsExport.ColaboradorSOAP.InserirRequest request) {
            return base.Channel.Inserir(request);
        }
        
        public void Inserir(DoorsExport.ColaboradorSOAP.Colaborador colaborador) {
            DoorsExport.ColaboradorSOAP.InserirRequest inValue = new DoorsExport.ColaboradorSOAP.InserirRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.InserirRequestBody();
            inValue.Body.colaborador = colaborador;
            DoorsExport.ColaboradorSOAP.InserirResponse retVal = ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).Inserir(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.InserirResponse> DoorsExport.ColaboradorSOAP.ColaboradorSoap.InserirAsync(DoorsExport.ColaboradorSOAP.InserirRequest request) {
            return base.Channel.InserirAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.InserirResponse> InserirAsync(DoorsExport.ColaboradorSOAP.Colaborador colaborador) {
            DoorsExport.ColaboradorSOAP.InserirRequest inValue = new DoorsExport.ColaboradorSOAP.InserirRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.InserirRequestBody();
            inValue.Body.colaborador = colaborador;
            return ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).InserirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoorsExport.ColaboradorSOAP.InserirVariosResponse DoorsExport.ColaboradorSOAP.ColaboradorSoap.InserirVarios(DoorsExport.ColaboradorSOAP.InserirVariosRequest request) {
            return base.Channel.InserirVarios(request);
        }
        
        public int InserirVarios(DoorsExport.ColaboradorSOAP.Colaborador[] colaborador) {
            DoorsExport.ColaboradorSOAP.InserirVariosRequest inValue = new DoorsExport.ColaboradorSOAP.InserirVariosRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.InserirVariosRequestBody();
            inValue.Body.colaborador = colaborador;
            DoorsExport.ColaboradorSOAP.InserirVariosResponse retVal = ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).InserirVarios(inValue);
            return retVal.Body.InserirVariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.InserirVariosResponse> DoorsExport.ColaboradorSOAP.ColaboradorSoap.InserirVariosAsync(DoorsExport.ColaboradorSOAP.InserirVariosRequest request) {
            return base.Channel.InserirVariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.InserirVariosResponse> InserirVariosAsync(DoorsExport.ColaboradorSOAP.Colaborador[] colaborador) {
            DoorsExport.ColaboradorSOAP.InserirVariosRequest inValue = new DoorsExport.ColaboradorSOAP.InserirVariosRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.InserirVariosRequestBody();
            inValue.Body.colaborador = colaborador;
            return ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).InserirVariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoorsExport.ColaboradorSOAP.AtualizarResponse DoorsExport.ColaboradorSOAP.ColaboradorSoap.Atualizar(DoorsExport.ColaboradorSOAP.AtualizarRequest request) {
            return base.Channel.Atualizar(request);
        }
        
        public bool Atualizar(DoorsExport.ColaboradorSOAP.Colaborador colaborador) {
            DoorsExport.ColaboradorSOAP.AtualizarRequest inValue = new DoorsExport.ColaboradorSOAP.AtualizarRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.AtualizarRequestBody();
            inValue.Body.colaborador = colaborador;
            DoorsExport.ColaboradorSOAP.AtualizarResponse retVal = ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).Atualizar(inValue);
            return retVal.Body.AtualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.AtualizarResponse> DoorsExport.ColaboradorSOAP.ColaboradorSoap.AtualizarAsync(DoorsExport.ColaboradorSOAP.AtualizarRequest request) {
            return base.Channel.AtualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoorsExport.ColaboradorSOAP.AtualizarResponse> AtualizarAsync(DoorsExport.ColaboradorSOAP.Colaborador colaborador) {
            DoorsExport.ColaboradorSOAP.AtualizarRequest inValue = new DoorsExport.ColaboradorSOAP.AtualizarRequest();
            inValue.Body = new DoorsExport.ColaboradorSOAP.AtualizarRequestBody();
            inValue.Body.colaborador = colaborador;
            return ((DoorsExport.ColaboradorSOAP.ColaboradorSoap)(this)).AtualizarAsync(inValue);
        }
    }
}
